export const initStates = {
  name: "Aman",
  Boolean: false,
  date: true,
  app: true,
  click: true,
  request: true,
  response: true,
  impression: true,
  revenue: true,
  rate: true,
  ctr: true,
  startDate: new Date(),
  endDate: new Date(),
};
